
DROP TABLE CLASS_TBL;
DROP TABLE SUBJECT_TBL;
DROP TABLE STUDENT_TBL;



CREATE TABLE STUDENT_TBL (
    STU_NO   NUMBER NOT NULL,
    STU_NAME VARCHAR2(15 BYTE),
    STU_AGE  NUMBER,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO)
);

CREATE TABLE SUBJECT_TBL (
    SUB_SUBCO VARCHAR2(10 BYTE) NOT NULL,
    SUB_SUB   VARCHAR2(10 BYTE),
    SUB_T     VARCHAR2(10 BYTE),
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_SUBCO)
 );   

CREATE TABLE CLASS_TBL (
    CLA_APP   NUMBER NOT NULL,
    STU_NO    NUMBER,
    SUB_SUBCO VARCHAR2(10 BYTE),
    CONSTRAINT PK_CLASS PRIMARY KEY(CLA_APP),
    CONSTRAINT FK_CLASS_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT_TBL(STU_NO),
    CONSTRAINT FK_CLASS_SUBJECT FOREIGN KEY(SUB_SUBCO) REFERENCES SUBJECT_TBL(SUB_SUBCO)
    
);
